### PR TITLE
Add dask config extension to sphinx theme

### LINKED ISSUE #63: Add dask-config-sphinx extension to Dask-sphinx-theme
The dask/dask codebase has an [extension](https://github.com/dask/dask/blob/main/docs/source/ext/dask_config_sphinx_ext.py) that is useful in rendering dask configurations (from yaml) in the docs page. 

Given that other downstream libraries also use Dask's configuration module and might want to use the same extension to render these configs it might make sense to include with the dask-sphinx-theme that would enable other consumers of dask config to use this utility as well.

In my case I'd like to use this for [dask-sql](https://github.com/dask-contrib/dask-sql) that's moving towards using Dask's config.

cc: @quasiben @jacobtomlinson

### PR DESCRIPTION
**Pull request by quasiben**
closes #63 

Adds the config extension from https://github.com/dask/dask/pull/6069 to the dask theme.  Note, this will require a dask-sphinx-theme release before we are able to use in dask/dask or any dask project

cc @jacobtomlinson

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Nice, thanks @quasiben! I like the idea of making it easier for other projects to use the config extension.

Do you know if it's possible for other projects, which aren't using `dask-sphinx-theme` as their documentation theme, but do integrate with Dask's config system to still take advantage of this extension? My guess is "yes", but wanted to double check with you 

Also, could you add a snippet to the `README` which documents how this extension should be used? For example, over in `dask/dask` we have things like


```rst

Dask
~~~~

.. dask-config-block::
    :location: dask
    :config: https://raw.githubusercontent.com/dask/dask/main/dask/dask.yaml
    :schema: https://raw.githubusercontent.com/dask/dask/main/dask/dask-schema.yaml


Distributed Client
~~~~~~~~~~~~~~~~~~

.. dask-config-block::
    :location: distributed.client
    :config: https://raw.githubusercontent.com/dask/distributed/main/distributed/distributed.yaml
    :schema: https://raw.githubusercontent.com/dask/distributed/main/distributed/distributed-schema.yaml
```

**Comment by jacobtomlinson** [comment]
Thanks for handling this @quasiben.

@jrbourbeau this plugin is orthogonal to the theme itself, it just adds a new directive. You should be able to use this extension independently of which theme you configure. It just felt like this was a natural place for Dask Sphinx things to live.

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
This is now in `2.0.3` which is on PyPI and should be on Conda Forge later.

**Comment by jrbourbeau** [comment]
> You should be able to use this extension independently of which theme you configure

Great, that's what I thoughts -- just wanted to double check. Can we add documentation on this new directive?

**Comment by jacobtomlinson** [comment]
I've raised #66 to track this

**Pull request merged**
