### PR TITLE
Remove bits from layout that should be inherited from RTD

### PR DESCRIPTION
**Pull request by gforsyth**
I'm not sure if this will fix the font issues on dask.org but I think it will rule out some potential issues.

I thought I had removed the stuff that Jacob had to add in to fix the flicker-on-load issue, but a closer look shows me there's a bunch of extra stuff we probably don't need in our `layout.html` so I've removed that here.

@jrbourbeau if this looks ok to you we can try to merge and see if it fixes things.

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Sure, we can give this a try. Just got my own understanding, it looks like we're removing code that we're now inheriting from `sphinx-rtd-theme`?

The Dask docs look normal when building them locally with this PR (though I'm not able to reproduce the Chrome issue locally)

**Comment by gforsyth** [comment]
> Just got my own understanding, it looks like we're removing code that we're now inheriting from `sphinx-rtd-theme`?

That's my intention and I can also build the docs cleanly locally with this version (but I also can't reproduce the Chrome stuff locally)

**Review by jrbourbeau — APPROVED** [review]
Alright, let's give this a shot

**Comment by jsignell** [comment]
Nice!

**Pull request merged**
