### PR TITLE
Update theme for rebranding

### PR DESCRIPTION
**Pull request by scharlottej13**
Update Dask docs design in line with rebranding efforts in https://github.com/dask/community/issues/220. Changes include updated Dask logo, color palettes, and fonts.

To do:
- [ ] update icons
- [ ] update syntax highlighting (see #69)
- [ ] buttons for "next" and "previous" pages-- these look nice in the design doc, see
[Dask-Doc Portal Spec Sheet.pdf](https://github.com/dask/dask-sphinx-theme/files/8815476/Dask-Doc.Portal.Spec.Sheet.pdf), but I'm not sure how to recreate them

Here are a couple screenshots for comparison:

**current docs**
Screen Shot 2022-05-05 at 3 44 26 PM

**changes in this PR**
Screen Shot 2022-05-31 at 10 49 45 PM

cc @jacobtomlinson @AdiReske @jrbourbeau @jsignell

### CODE REVIEW

**Comment by AdiReske** [comment]
Thank you!!

**Review by jacobtomlinson — APPROVED** [review]
This looks great thanks @scharlottej13.

I see you have a few unchecked tasks but I would be more than happy to merge this as is and iterate after that. 

I'll merge this on Monday as part of the new website rollout.

**Comment by scharlottej13** [comment]
Sounds good @jsignell and @jacobtomlinson, thanks for taking a look!

Since @jrbourbeau fixed the RTD build, if you (or others) have bandwidth to click through some of the docs pages, that would be great. Of course, I can also make more changes after "going live" on 6/6.

**Comment by scharlottej13** [comment]
> The docs won't be rebuilt until the next release unless we specifically trigger them in readthedocs.

@jsignell does this mean triggering a docs build separately for each project (e.g. `dask-ml`, dask-distributed`, etc.)? And, if so, @jacobtomlinson does it make sense to merge these PRs today or tomorrow instead? I haven't triggered a rebuild in readthedocs before (I don't think I have permission to do so), but happy to do so if someone doesn't mind walking me through the steps.

cc @jrbourbeau

**Comment by jacobtomlinson** [comment]
Id rather wait until the website is live on Monday. 

We need to merge here, tag a release, potential update pinned versions in downstream projects and then rebuild the docs sites on each of those. 

In most cases rebuilding the downstream docs sites involves merging a PR to main.

**Comment by scharlottej13** [comment]
> We need to merge here, tag a release, potential update pinned versions in downstream projects and then rebuild the docs sites on each of those.

I can open up PRs to update the pinned versions in downstream projects. From the [release history](https://pypi.org/project/dask-sphinx-theme/#history) looks like it will be `2.0.4`?

> In most cases rebuilding the downstream docs sites involves merging a PR to main.

@jacobtomlinson would it be helpful for me to open placeholder PRs in downstream docs sites to make this easier? The downstream sites I have include (going down the list of repos):

- [ ] distributed
- [ ] dask-tutorial
- [ ] dask-kubernetes
- [ ] dask-cloudprovider
- [ ] dask-ml
- [ ] dask-gateway
- [ ] dask-examples
- [ ] dask-image
- [ ] dask-stories
- [ ] dask-blog
- [ ] dask-mpi
- [ ] dask-jobqueue
- [ ] dask-yarn
- [ ] ? dask-glm 

Also, thanks for answering all my questions! Just trying to figure out what the steps are and how I can help.

**Comment by jacobtomlinson** [comment]
That would be super helpful! Anything that's not marked as archived on GitHub will need updating. 

I think given this is a major rebrand we should tag version `3.0.0` though.

**Pull request merged**
